sudo: required
services:
  - docker

before_install:
  - docker build -t 123saketh/mutli-docker -f ./client/Dockerfile.dev ./client

scripts:
  - docker run 123saketh/mutli-docker npm run test -- --watchAll=false

after_success:
  - docker build -t 123saketh/mutli-client ./client
  - docker build -t 123saketh/mutli-nginx ./nginx
  - docker build -t 123saketh/mutli-server ./server
  - docker build -t 123saketh/mutli-worker ./worker
  #login into docker cli
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  #push images to docker hub
  - docker push 123saketh/mutli-client
  - docker push 123saketh/mutli-nginx 
  - docker push 123saketh/mutli-server
  - docker push 123saketh/mutli-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: mutli-docker
  env: Mutlidocker-env
  bucket_name: elasticbeanstalk-us-east-2-883847302082
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


